name: Präsentation 0902
slug: pr-sentation-0902-0902
client: fzag-staging
project_number: 0902
languages:
- de
default_language: de
description:
  de: Präsentation 0902
  en: Präsentation 0902
master_slug: master-standard
master_version: v20260828-01
